### ISSUE TITLE
Logo text not visible in dark mode

### ISSUE THREAD

**Issue by wbt** [supermodularxyz/pgn-docs#3]
Text visible in light mode:
![image](https://github.com/supermodularxyz/pgn-docs/assets/563406/b3c79de2-7774-4eb1-a892-9735552af2ec)
has insufficient contrast in dark, 
![image](https://github.com/supermodularxyz/pgn-docs/assets/563406/e67324a4-40fb-4686-9191-f0db76986abe)

because the SVG which defines those glyphs uses `fill="black"` and black-on-black is hard to see.  The compression involved in the image files of these screenshots makes it considerably easier to see than when viewed on the webpage.

**Comment by brunz-me** [comment]
This has been resolved :)
